apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  labels:
    app: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:13-alpine
        command: ['sh', '-c']
        args:
          - |
            echo "Waiting for database to be ready..."
            until pg_isready -h $(POSTGRES_HOST) -p $(POSTGRES_PORT) -U postgres; do
            echo "Waiting for database to start..."
              sleep 2
              done
          - echo "Database is ready"
        env:
        - name: PGPASSWORD
          value: $(POSTGRES_PASSWORD)
        envFrom:
          - configMapRef:
              name: common-config
          - secretRef:
              name: common-secrets
      containers:
      - name: rest
        image: postgrest/postgrest
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "2Gi"
        #     cpu: "500m"
        env:
        - name: PGRST_DB_URI
          value: postgres://authenticator:$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
        - name: PGRST_DB_SCHEMAS
          value: $(PGRST_DB_SCHEMAS)
        - name: PGRST_DB_ANON_ROLE
          value: anon
        - name: PGRST_JWT_SECRET
          value: $(JWT_SECRET)
        - name: PGRST_DB_USE_LEGACY_GUCS
          value: "false"
        - name: PGRST_APP_SETTINGS_JWT_SECRET
          value: $(JWT_SECRET)
        - name: PGRST_APP_SETTINGS_JWT_EXP
          value: $(JWT_EXPIRY)
        envFrom:
          - configMapRef:
              name: common-config
          - secretRef:
              name: common-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: rest
spec:
  selector:
    app: rest
  ports:
    - port: 3000
      targetPort: 3000
